ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed

version = 17

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "startmichlogo"
file = "images/startmichlogo.png"
startx = 393
starty = 253
priority = 2
